### ISSUE TITLE
Does not work for sites other than youtube

### ISSUE THREAD

**Issue by HASJ** [lostb053/ytdl-termux#2]
It always prompts if you want video/audio and then it prompts for quality selection, making it fail even generic video hosts, like a direct link do the video file or sites like Imgur/gfycat.
How do I uninstall it?

**Comment by lostb053** [comment]
Ahh sorry i left development in middle
Ok
U wanna uninstall it
Right?

`rm -rf $PREFIX/bin/ytdl $PREFIX/etc/ytdlversion bin`
Should do the trick

**Comment by lostb053** [comment]
Ping me if it doesn't work

**Comment by lostb053** [comment]
And yes, i made it just for yt, none else

**Comment by HASJ** [comment]
> Ping me if it doesn't work

Didn't work. :(

**Comment by lostb053** [comment]
Wdym?

**Comment by lostb053** [comment]
Can give ss for error or something?
Or show me how it didn't work

**Comment by HASJ** [comment]
> Can give ss for error or something? Or show me how it didn't work

![Screenshot_2022-12-02-03-00-37-674_com miui gallery](https://user-images.githubusercontent.com/9345660/205225685-ef1d7bb8-b423-4eeb-8ac5-747e2f2a780e.jpg)

**Comment by lostb053** [comment]
Ok, try opening termux
And enter ytdl cmd
Tell me if it gives you something

**Comment by lostb053** [comment]
Don't share link to termux, open termux app and enter cmd

**Comment by HASJ** [comment]
> Ok, try opening termux And enter ytdl cmd Tell me if it gives you something

![IMG_20221202_030354](https://user-images.githubusercontent.com/9345660/205226070-38925c46-8221-4d47-8591-4eb556a7cd2c.jpg)

**Comment by lostb053** [comment]
Good, try doing
ls ~/bin

**Comment by HASJ** [comment]
> Good, try doing ls ~/bin

![IMG_20221202_030614](https://user-images.githubusercontent.com/9345660/205226349-64c1cd0b-005d-4be1-8af3-42f1b1835011.jpg)

**Comment by lostb053** [comment]
Ok, perfect

rm -rf ~/bin

**Comment by HASJ** [comment]
Done

**Comment by lostb053** [comment]
Worked?

**Comment by lostb053** [comment]
Try now, should be out of system

**Comment by HASJ** [comment]
Thanks I'll just reinstall termux

**Comment by lostb053** [comment]
Well, not my place to say anything, do as u wish

**Comment by HASJ** [comment]
> Wait, why? You'll loose the theme too

I like it, will just install separately

**Comment by lostb053** [comment]
Alright, termux is kinda boring without it
