### ISSUE TITLE
[Question] Why your program need screen overlay permission?

### ISSUE THREAD

**Issue by HaiziIzzudin** [lostb053/ytdl-termux#3]
Just asking :D

**Comment by lostb053** [comment]
Haha, good question.
So yes, it has a file in it termux-url-opener, for which to function screen overlay permission is required.


What that file does?
It allows you to share a YouTube video directly from website or YouTube to termux and download it. (Sorry but at the moment, playlist is not supported at all, don't even know if code still works)

Try this,
1. Go to YouTube
2. Share a video from YouTube to termux
3. It will show you options for download

You don't need to copy link, then ytdl, choose options then paste link
When u share it, link gets saved


Where exactly is that permission used?
The file termux-url-opener displays a screen overlay window (kind of temporary session), which gets terminated as soon as you leave it or the process associated with it is completed. Thus it's adviced to wait till window closes on its own for successful download.

**Comment by lostb053** [comment]
Hope that helps. I'm no expert or something. That's just what i experienced
